### ISSUE TITLE
nothing output

### ISSUE THREAD

**Issue by Instantnoodles-madman** [noahleigh/glitch_me#1]
when Add glitch effects to a single image and save by command "python3 -m glitch_me still /pictures/1.jpg /pictures",it  output nothing with no error

**Comment by noelleleigh** [comment]
Hi @Instantnoodles-madman , thanks for reaching out. 

I've reproduced your issue by using an input pattern that doesn't match any files. I've just released v1.1.1 which should now throw an error when that happens, to make it clear what the issue was.

Can you pull the latest changes from the repository and try again?

**Comment by Instantnoodles-madman** [comment]
> Can you pull the latest changes from the repository and try again?
i have tried it again，and it throw an error indeed,
i want to know is there some else rule to follow? what is  requirements of the location of file"pictures"?Isn't it in the file " glitch_me"?
my case:
No install   and add glitch effects to a single image and save it to its existing directory by the code:
python3 -m glitch_me still /pictures/1.png /pictures 
but it gave the error :No files found that matched the input pattern "/pictures/1.png"

**Comment by noelleleigh** [comment]
@Instantnoodles-madman I noticed you posted a comment, but deleted it. Did you manage to solve your issue?

**Comment by Instantnoodles-madman** [comment]
> @Instantnoodles-madman I noticed you posted a comment, but deleted it. Did you manage to solve your issue?
yes！I run it successfully, thank you very much!

**Comment by noelleleigh** [comment]
Glad to hear it! I’ll close this issue now.
