### ISSUE TITLE
Pip install errror

### ISSUE THREAD

**Issue by 1Danish-00** [noahleigh/glitch_me#2]
pip install -e ./glitch_me

Not working

**Comment by noelleleigh** [comment]
Hi!

I'm going to need a bit more information from you to troubleshoot what's going on:

1. What operating system are you using?
2. How did you install Python?
3. Copy and paste the output from running `pip install -e ./glitch_me` so I can see specifically what the problem was.

**Comment by 1Danish-00** [comment]
1. Debian Linux 10 (buster) x86_64
2. Python 3.9.2
    pip 21.0.1

3.  ERROR: ./glitch_me is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by 1Danish-00** [comment]
> Hi!
> 
> I'm going to need a bit more information from you to troubleshoot what's going on:
> 
> 1. What operating system are you using?
> 2. How did you install Python?
> 3. Copy and paste the output from running `pip install -e ./glitch_me` so I can see specifically what the problem was.

1. Debian Linux 10 (buster) x86_64
2. Python 3.9.2
    pip 21.0.1

3.  ERROR: ./glitch_me is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by noelleleigh** [comment]
Are you running `pip install` from inside the `glitch_me` folder? For that syntax to work, it needs to be run _outside_ that directory.

So the sequence of commands is:

```bash
git clone https://github.com/noelleleigh/glitch_me.git
pip install -e ./glitch_me
```

With no `cd` in between.

**Comment by 1Danish-00** [comment]
> Are you running `pip install` from inside the `glitch_me` folder? For that syntax to work, it needs to be run _outside_ that directory.
> 
> So the sequence of commands is:
> 
> ```shell
> git clone https://github.com/noelleleigh/glitch_me.git
> pip install -e ./glitch_me
> ```
> 
> With no `cd` in between.

Okk it worked thanks 😊
But better make it Directly install from pip

**Comment by noelleleigh** [comment]
> Okk it worked thanks 😊

Glad to hear it! Feel free to share any cool images you make with it!

> But better make it Directly install from pip

I tried to a while ago, but wasn't able to get it to publish with the README in Markdown format, so I gave up.
